version: '3.4'

services:
  mysql:
    container_name: mysql
    platform: linux/x86_64
    networks:
      - lession
    image: mysql
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports: 
      - "3306:3306"
    env_file:
        - ../.env
  
  adminer:
    container_name: adminer
    image: adminer
    networks:
      - lession
    restart: always
    ports:
      - 81:8080

networks:
  lession:
    driver: bridge
